# Generated by Django 3.0.5 on 2020-04-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_parent_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='parent',
            new_name='user',
        ),
    ]
